version: '3'
services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  azure-storage:
    image: video-storage
    build: 
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - STORAGE_ACCOUNT_NAME=bmdksergio1
      - STORAGE_ACCESS_KEY=mNAxjsUknOpY37NPJlIG72fx3pTxLUHSo1IQoPkaJJS6XTZ3MP2SRgVVZZQLezLiXjzPsLYll7lq+ASt/qxRfA==
      
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=4001
      - URI=mongodb://db:27017
    restart: "no"
# conect to compas->localhost = mongodb://localhost:4000