version: '3'
services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  # azure-storage:
  #   image: video-storage
  #   build: 
  #     context: ./video-storage
  #     dockerfile: Dockerfile
  #   container_name: video-storage
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     - PORT=4001
  #     - STORAGE_ACCOUNT_NAME=bmdksergio1
  #     - STORAGE_ACCESS_KEY=mNAxjsUknOpY37NPJlIG72fx3pTxLUHSo1IQoPkaJJS6XTZ3MP2SRgVVZZQLezLiXjzPsLYll7lq+ASt/qxRfA==
      
  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/videos:/usr/src/app/videos:z
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=4001
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
    restart: "no"
  history:
    image: history
    build: 
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      # - ./:/root/.npm:z
      - ./history:/usr/src:z
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=history
    depends_on:
      - db
    restart: "no"
# conect to compas->localhost = mongodb://localhost:4000